name: Build and Push Docker Images

on:
  push:
    branches: 
      - main

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # ← 差分取得のために全履歴を取る
      - name: Get changed subdirectories
        id: set-matrix
        run: python .github/scripts/list_up_updated_folders.py
        env:
          GITHUB_OUTPUT: ${{ github.output }}

  run-on-updated:
    needs: generate-matrix
    if: needs.generate-matrix.outputs.matrix != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Run job for ${{ matrix.dir }}
        run: |
          echo "Changed dir: ${{ matrix.dir }}"
          ls dockerfiles/${{ matrix.dir }}
  
#  build:
#    needs: generate-matrix
#    runs-on: ubuntu-latest
#    strategy:
#      matrix: ${{ fromJson(needs.detect_dirs.outputs.matrix) }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      - name: Log in to GitHub Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Build and push image
#        uses: docker/build-push-action@v2
#        with:
#          context: ${{ matrix.folder }}
#          file: ${{ matrix.folder }}/Dockerfile
#          push: true
#          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.folder }}:${{ matrix.tag }}