name: Build and Push Docker Images

on:
  push:
    branches: 
      - main
    paths:
      - 'directory1/**'
      - 'directory2/**'
      - '.github/workflows/docker-image.yml'

jobs:
  detect_dirs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Detect directories
        id: detect
        run: |
          dirs=$(find . -maxdepth 2 -type f -name Dockerfile | xargs -n1 dirname | sed 's|^\./||')
          matrix="{\"include\":["
          first=1
          for d in $dirs; do
            if [ $first -eq 0 ]; then
              matrix+=","
            fi
            tag=$( [ -f "$d/configfile" ] && grep -E 'TAG=' "$d/configfile" | cut -d '=' -f2 || echo "latest" )
            matrix+="{\"folder\":\"$d\", \"tag\":\"$tag\"}"
            first=0
          done
          matrix+="]}"
          echo "Matrix: $matrix"
          echo "::set-output name=matrix::$matrix"
      - name: Set matrix output
        run: echo "Matrix generated"
  build:
    needs: detect_dirs
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.detect_dirs.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.folder }}
          file: ${{ matrix.folder }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.folder }}:${{ matrix.tag }}